---
name: Test
# This Workflow was written by CSykes
on:
  pull_request:
    branches-ignore : ['gh-pages']

jobs:
  BuildAndTest:
    runs-on: windows-latest
    
    steps:
          
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal
      
      - name: use this action, test solution dir
        uses: zyborg/dotnet-tests-report@v1
        with:
          project_path: tests/NUnitTestRunnerTests
          report_name: Tests
          report_title: Tests
          github_token: ${{ secrets.GITHUB_TOKEN }}